[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/nfactor26"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/nfactor26"

[social.params]
icon = "brand-twitter"